#-----------------------------------------------------------------------------------------------------------------
# Example configuration for spinnaker public facing URLs.
#-----------------------------------------------------------------------------------------------------------------
apiVersion: spinnaker.io/v1alpha2
kind: SpinnakerService
metadata:
  name: spinnaker
spec:
  spinnakerConfig:
    config:
      security:
        apiSecurity:
          overrideBaseUrl: https://172.17.0.57/api # Public API (Gate) url. Using the same hostname for deck and gate only works when exposing spinnaker with ingress.
          corsAccessPattern: https://172.17.0.57
        uiSecurity:
          overrideBaseUrl: https://172.17.0.57 # Public UI (Deck) url.
    profiles:
      gate:
        server:
          servlet:
            context-path: /api
    service-settings:
      gate:
        healthEndpoint: /api/health
